const SHOW_DATA="SHOW_DATA";        //用常量定义这些字符串，这样以后来修改这些字符串方便查找。
const SHOW_STUDENT="SHOW_STUDENT";
const SHOW_ONESTUDENT="SHOW_ONESTUDENT";
const SHOW_PAGE="SHOW_PAGE";
const SHOW_EIT="SHOW_EIT";
const SHOW_SERCHDATA="SHOW_SERCHDATA";
const THEATRECHAIN_DATA="THEATRECHAIN_DATA";  //院线匹配 电影数据。
const THEATRECHAIN_DELMOVIE="THEATRECHAIN_DELMOVIE";  //院线匹配 删除电影的数据。
export {SHOW_DATA,SHOW_STUDENT,SHOW_ONESTUDENT,SHOW_PAGE,SHOW_EIT,SHOW_SERCHDATA,THEATRECHAIN_DATA,THEATRECHAIN_DELMOVIE}





