const SHOW_DATA="SHOW_DATA";        //用常量定义这些字符串，这样以后来修改这些字符串方便查找。
const SHOW_STUDENT="SHOW_STUDENT";
const SHOW_ONESTUDENT="SHOW_ONESTUDENT";
const SHOW_PAGE="SHOW_PAGE";
const SHOW_EIT="SHOW_EIT";
const SHOW_SERCHDATA="SHOW_SERCHDATA";
const THEATRECHAIN_DATA="THEATRECHAIN_DATA";  //院线匹配 电影数据。
const THEATRECHAIN_DELMOVIE="THEATRECHAIN_DELMOVIE";  //院线匹配 删除电影的数据。
const USER_DATA = "USER_DATA";    //用户数据【账号+密码】
const USER_DELDATA = "USER_DELDATA";  //需要删除的数据
const USER_PAGEDATA = "USER_PAGEDATA";  //用户管理页码
const USER_SEACHDATA = "USER_SEACHDATA";  //用户管理 搜索信息
const USER_CHANGEDATA = "USER_CHANGEDATA"; //用户管理 修改信息
const HOTMOIVE_SHOWDATA = "HOTMOIVE_SHOWDATA";//热映电影总数据
const HOTMOIVE_ADDDATA = "HOTMOIVE_ADDDATA";//热映添加电影总数据
const HOTMOIVE_DELETE = "HOTMOIVE_DELETE";//热映电影删除
const HOTMOIVE_SEARCH = "HOTMOIVE_SEARCH";//热映电影搜索
export {SHOW_DATA,SHOW_STUDENT,SHOW_ONESTUDENT,SHOW_PAGE,SHOW_EIT,SHOW_SERCHDATA,THEATRECHAIN_DATA,THEATRECHAIN_DELMOVIE,USER_DATA,USER_DELDATA,USER_PAGEDATA,USER_SEACHDATA,USER_CHANGEDATA,HOTMOIVE_SHOWDATA,HOTMOIVE_ADDDATA,HOTMOIVE_DELETE,HOTMOIVE_SEARCH}

