const SHOW_DATA="SHOW_DATA";        //用常量定义这些字符串，这样以后来修改这些字符串方便查找。
const SHOW_STUDENT="SHOW_STUDENT";
const SHOW_ONESTUDENT="SHOW_ONESTUDENT";
const HOTMOIVE_SHOWDATA = "HOTMOIVE_SHOWDATA";//热映电影总数据
const HOTMOIVE_ADDDATA = "HOTMOIVE_ADDDATA";//热映添加电影总数据
export {SHOW_DATA,SHOW_STUDENT,SHOW_ONESTUDENT,HOTMOIVE_SHOWDATA,HOTMOIVE_ADDDATA}